# Generated by Django 5.1.7 on 2025-03-10 11:45

import django.db.models.deletion
import packages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=packages.models.generate_tracking_number, editable=False, max_length=50, unique=True)),
                ('sender_name', models.CharField(help_text="Sender's full name", max_length=200)),
                ('sender_address', models.TextField(help_text="Sender's address")),
                ('sender_city', models.CharField(blank=True, help_text="Sender's city", max_length=100, null=True)),
                ('sender_zip_code', models.CharField(blank=True, help_text="Sender's zip code", max_length=20, null=True)),
                ('sender_phone_number', models.CharField(blank=True, help_text="Sender's phone number", max_length=20, null=True)),
                ('sender_email', models.EmailField(blank=True, help_text="Sender's email", max_length=254, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_address', models.TextField()),
                ('receiver_city', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the package', null=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Charge for the package delivery', max_digits=10)),
                ('issued_by', models.ForeignKey(help_text='Employee who issued the package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
